name: Deploy
on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          submodules: true
      
      - uses: actions/checkout@v4
        with:
          repository: openfl/openfl
          path: openfl
          ref: dev
      
      - uses: actions/checkout@v4
        with:
          repository: openfl/lime
          path: lime
          ref: 8.1.3
      
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Set HAXEPATH
        run: |
          echo "HAXEPATH=$HAXE_STD_PATH/.." >> $GITHUB_ENV

      - name: Install Haxe dependencies
        run: |
          haxelib install dox 1.6.0
          haxelib dev lime lime
          haxelib dev openfl openfl

      - name: Build docs
        working-directory: openfl/scripts
        run: |
          haxe docs.hxml
      
      - name: Prepare deploy
        run: |
          mkdir deploy
          cp -r openfl/docs/* deploy
          cp CNAME deploy/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
