name: Test deployment
on: [pull_request]

jobs:
  test-deploy:

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - uses: actions/checkout@v2
        with:
          repository: openfl/openfl
          path: openfl
          ref: 9.1.0
      
      - uses: actions/checkout@v2
        with:
          repository: openfl/lime
          path: lime
          ref: 7.9.0
      
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.5

      - name: Set HAXEPATH
        run: |
          echo "HAXEPATH=$HAXE_STD_PATH/.." >> $GITHUB_ENV

      - name: Install Haxe dependencies
        run: |
          haxelib install dox 1.4.0
          haxelib dev lime lime
          haxelib dev openfl openfl
      
      - name: Build docs
        working-directory: openfl/scripts
        run: |
          haxe docs.hxml